# Single-user notebook image spawned by DockerSpawner (DOCKER_JUPYTER_IMAGE).
ARG BASE_IMAGE=quay.io/jupyter/minimal-notebook:latest
FROM ${BASE_IMAGE}

# JupyterLab markdown-it renderer (https://pypi.org/project/jupyterlab-markup/)
RUN pip install --no-cache-dir jupyterlab-markup
